# Dev
FROM python:3.11-slim

# Create non-root user and working directory
RUN useradd --create-home --shell /bin/bash python

# Setting User and Working Directory
USER python
WORKDIR /home/python

# Copy Source files
COPY requirements.txt .
COPY ./*.py .

# Install Packages
RUN pip install -r requirements.txt

# Setting PATH
ENV PATH="/home/python/.local/bin:$PATH"

# Expression PORT
EXPOSE 5000

# Run Application in local for development
CMD [ "python", "app.py" ]