apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: api
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: mysql
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-player
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  serviceName: 
  template:
    metadata:
      name: mysql-api
      labels:
        app: mysql
    spec:
      containers:
        - image: hyukjun/mysql-8.2.0-init-scheme-amd64:1.0
          name: mysql
          ports:
          - containerPort: 3306
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 500Mi
          envFrom:
            - secretRef:
                name: mysql-context
          volumeMounts:
            - name: playerdb-vol
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: playerdb-vol
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: azurefile
      resources:
        requests:
          storage: 512Mi